name: Tectonigrated
main: org.peak15.tectonigrated.Tectonigrated
version: 1.0
author: HOLOGRAPHICpizza (Michael Craft - mcraft@peak15.org)
description: >
             Tectonicus integration for Bukkit.
commands:
  rendermap:
    description: Starts a map render.
    usage: |
           /<command>
permissions:
  tectonigrated.render:
    description: Allows the player to render the map
    default: op